kind: pipeline
steps:
  - name: build
    image: maven:3.6.2-jdk-8
    commands:
      - mvn clean package
    volumes:
      - name: mavenrep
        path: /root/.m2
    when:
      branch: main
      event: [ push ]
  - name: docker
    image: plugins/docker
    settings:
        repo: garzhi/drone-demo
        use_cache: true
        username: root
        password: Mm25613891
        tags:
          - latest
    commands:
      - docker build -t garzhi/drone-demo
      - java -jar version_hit-0.0.1-SNAPSHOT.jar 
    when:
      branch: main
      event: [ push ]
