kind: pipeline
type: docker
name: SpringDeploy_GarZhi

steps:
  - name: build
    image: maven:ibmjava-alpine
   # image: garzhi/web-demo:6
    volumes:
      # maven 构建缓存
      - name: cache
        path: /root/.m2
      # 数据
      - name: data
        path: /home
    commands:
      - mvn clean package -Dmaven.test.skip=true
      - (rm -f /home/*.jar /home/Dockerfile) || true
      - cp target/*.jar /home
      - cp Dockerfile /home
    when:
      branch: main
      event: [push]
   
  - name: ssh-deploy
    image: appleboy/drone-ssh:1.5.7
    settings:
      host: 1.116.220.137
      username: root
      password:
        from_secret: password
      port: 22
      script:
        - cd /root/DockerWorkbench/
        - docker image rm web-demo:7 || true
        - docker build -t web-demo:7 .
        - (docker container stop web-demo && docker container rm web-demo) || true
        - docker run -d -p 8081:8080 --name web-demo web-demo:7
    when:
      branch: main
      event: [push]


# 挂载的主机卷，可以映射到docker容器中
volumes:
   # maven构建缓存
   - name: cache
     host:
       path: /var/lib/cache
   # maven构建后与宿主机通信的共享目录
   - name: data
     host:
       path: /root/DockerWorkbench/

