steps:
  - name: build
    image: maven:3.6.2-jdk-8
    commands:
      - mvn clean package
    volumes:
      - name: mavenrep
        path: /root/.m2
    when:
      branch: main
      event: [ push ]
  - name: docker
    image: plugins/docker
    settings:
      username: 仓储登录用户
      password: 密码
      registry: 仓储服务地址
      insecure: true
      repo: 仓储路径
      build_args:
        - JAR_FILE: *.jar
    when:
      branch: master
      event: [ push ]
