kind: pipeline
name: deploy_Garzhi
steps:
  - name: build
    image: garzhi/web-demo:6
    commands:
      - mvn clean package
      - java -jar target/*.jar
    volumes:
      - name: mavenrep
        path: /root/.m2
    when:
      branch: main
      event: [push]
